version: '2'
services:
   webserivce:
       container_name: webserivce-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "443:8443"
       volumes:
       - ../target/WebService.jar:/root/target/WebService.jar
       networks:
       - java110-net
#       extra_hosts:
#       - "dev.java110.com:192.168.1.18"
#       - "dev.db.java110.com:192.168.1.18"
#       - "dev.zk.java110.com:192.168.1.18"
#       - "dev.kafka.java110.com:192.168.1.18"
#       - "dev.redis.java110.com:192.168.1.18"
#       - "api.java110.com:92.168.1.18"
networks:
  java110-net:
    external: true